site_name: Dac-Man
theme:
  name: material
  palette:
    primary: teal
nav:
  - Introduction: index.md
  - Installation:
    - Installing Dac-Man: install/index.md
    - Installing plug-in dependencies: install/dependencies.md
    - Updating Dac-Man: install/update.md
    - Testing the installation: install/test.md
  - Quickstart: quickstart.md
  - Using Dac-Man:
    - General use: use/general.md
    - On HPC clusters: use/hpc.md
    - Plug-ins: use/plugins.md
    - Comparing read-only datasets: use/read-only.md
    - Comparing datasets at different sites: use/different-sites.md
    - Customization: use/config.md
  - API:
      Dac-Man: api/dacman.md
      Plug-ins: api/plugins.md
  - Dac-Man Plug-ins:
    # - Introduction: plugins/introduction.md
    - Default: plugins/default.md
    - HDF5: plugins/hdf5.md
    - CSV: 
      - The CSV plug-in: plugins/csv/index.md
      - API: plugins/csv/api.md
    - Extending plug-ins: plugins/extend.md
  - Examples:
    - Using custom analysis scripts: examples/script.md
    - Adapting the CSV plug-in to custom data: examples/csv-simple.md
    - HDF5 and EDF files: examples/hdf5-edf.md
    # - CSV files: examples/csv.md
    # - Excel files: examples/excel.md
  - Plug-in documentation WIP:
    - Extending built-in plug-ins:
      - CSV: plugins-docs/extend/csv.md
      - HDF5: plugins-docs/extend/hdf5-edf.md
    - Creating a plug-in from scratch: plugins-docs/from-scratch.md
  - For developers:
    - Running tests: develop/tests.md
    - Documentation: develop/docs.md
  - Troubleshooting: troubleshooting.md
  - License: license.md

copyright: 'Copyright &copy; 2018--2019, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights reserved.'
repo_name: dghoshal-lbl/dac-man
repo_url: https://github.com/dghoshal-lbl/dac-man

extra:
  social:
    - type: globe
      link: http://deduce.lbl.gov

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
