site_name: Dac-Man
theme:
  name: material
  palette:
    primary: teal
nav:
  - Introduction: index.md
  - Installing Dac-Man: install/index.md
  - Testing the Installation: testing.md
  - Quickstart: quickstart.md
  - Extended Usage Scenarios:
    - Running Custom Change Analyses: use/plugins.md
    - Running in Parallel on HPC Clusters: use/hpc.md
    - Additional use cases: use/misc.md
  - Dac-Man Plug-ins:
    - Overview: plugins/overview.md
    # - Introduction: plugins/introduction.md
    - Installing plug-in dependencies: install/dependencies.md
    - Default: plugins/default.md
    - CSV: plugins/csv.md
    - Excel: plugins/excel.md
    - HDF5: plugins/hdf5.md
    - JSON: plugins/json.md
  #- Examples:
    # - Using custom analysis scripts: examples/script.md
    # - Adapting the CSV plug-in to custom data: examples/csv-simple.md
    # - HDF5 and EDF files: examples/hdf5-edf.md
    # - CSV files: examples/csv.md
    # - Excel files: examples/excel.md
    - Extending an included plug-in:
      - CSV: plugins/extend/csv.md
      - HDF5: plugins/extend/hdf5-edf.md
      - JSON: plugins/extend/json.md
    - Creating a plug-in from scratch: plugins/from-scratch.md
  - Reference:
      Commands and Output: reference/commands.md
      Dac-Man API: reference/dacman-api.md
      Plug-ins API: reference/plugins-api.md
  - Troubleshooting: troubleshooting.md
  - License: license.md

copyright: 'Copyright &copy; 2018--2020, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights reserved.'
repo_name: deduce-dev/dac-man
repo_url: https://github.com/deduce-dev/dac-man

extra:
  social:
    - icon: octicons/globe
      link: http://deduce.lbl.gov

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
