version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(levelname)s] %(message)s"
    basic:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: basic
        filename: dacman.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
root:
    level: INFO
    handlers: [console, file_handler]    